project:
  type: website
  output-dir: _site
  resources:
    - "contenido/*.ipynb"
    - "contenido/assets/*"

website:
  title: "Mis Notas de Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
      - text: "Clases"
        menu:
        - contenido/clase-01-20260313.ipynb
  page-footer:
    left: "Ciencia de Datos para Econ. y Neg. - Sidicaro Nicolás Leonardo"
    center: |
      [Repo oficial](https://github.com/nsidicarocep/curso_cdd_fce_uba_1c2026) |
      [Fork de este autor](https://github.com/victortizs/curso_cdd_fce_uba_2026_1c/tree/my-study-notes)
    right: "© 2026"

format:
  html:
    theme: cosmo
    toc: true
    lang: es
    code-fold: true    # Keeps code blocks collapsed until clicked
    code-tools:
      source: true     # Do not hide the raw source code of the page
      toggle: true     # Allows readers to hide/show code blocks