project:
  type: website
  output-dir: _site
  resources:
    - "contenido/*.ipynb"
    - "contenido/assets/*"

website:
  title: "Mis Notas de Ciencia de Datos"
  navbar:
    left:
      - href: index.qmd
      - text: "Clases"
        menu:
        - contenido/clase-00-20260313.ipynb
        - contenido/clase-01-20260317.ipynb
  page-footer:
    left: "Ciencia de Datos para Econ. y Neg. - Sidicaro Nicolás Leonardo"
    center:
      <a href="https://github.com/nsidicarocep/curso_cdd_fce_uba_1c2026" target="_blank" rel="noopener noreferrer">Repo oficial</a> |
      <a href="https://github.com/victortizs/curso_cdd_fce_uba_2026_1c" target="_blank" rel="noopener noreferrer">Fork de este autor</a>
    right: "© 2026"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    lang: es
    code-fold: true    # Keeps code blocks collapsed until clicked
    code-tools:
      source: false    # Hide/show the raw source code of the page
      toggle: false    # Allows readers to hide/show code blocks